//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavadoraLubricadora.LavadoraService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasesLavadora")]
    [System.SerializableAttribute()]
    public partial class Vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TipoMotorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnioField, value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVehiculo {
            get {
                return this.IdVehiculoField;
            }
            set {
                if ((this.IdVehiculoField.Equals(value) != true)) {
                    this.IdVehiculoField = value;
                    this.RaisePropertyChanged("IdVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TipoMotor {
            get {
                return this.TipoMotorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMotorField, value) != true)) {
                    this.TipoMotorField = value;
                    this.RaisePropertyChanged("TipoMotor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasesLavadora")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LavadoraLubricadora.LavadoraService.Cliente))]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasesLavadora")]
    [System.SerializableAttribute()]
    public partial class Cliente : LavadoraLubricadora.LavadoraService.Persona {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LavadoraService.ILavadoraService")]
    public interface ILavadoraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EditarProveedorResponse")]
        void EditarProveedor(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EditarProveedorResponse")]
        System.Threading.Tasks.Task EditarProveedorAsync(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EliminarProveedorResponse")]
        void EliminarProveedor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EliminarProveedorResponse")]
        System.Threading.Tasks.Task EliminarProveedorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProveedor", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProveedorResponse")]
        System.Data.DataTable ObtenerProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProveedor", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProveedorResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorNombreResponse")]
        System.Data.DataTable BuscarProveedorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorNombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorApellidoResponse")]
        System.Data.DataTable BuscarProveedorApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorApellidoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorRuc", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorRucResponse")]
        System.Data.DataTable BuscarProveedorRuc(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorRuc", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorRucResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorRucAsync(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresa", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresaResponse")]
        System.Data.DataTable BuscarProveedorEmpresa(string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresa", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorEmpresaAsync(string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerUsuarios", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerUsuariosResponse")]
        System.Data.DataTable ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerUsuarios", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/IngresarUsuarioResponse")]
        void IngresarUsuario(string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/IngresarUsuarioResponse")]
        System.Threading.Tasks.Task IngresarUsuarioAsync(string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EditarUsuarioResponse")]
        void EditarUsuario(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EditarUsuarioResponse")]
        System.Threading.Tasks.Task EditarUsuarioAsync(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EliminarUsuarioResponse")]
        void EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioNombreResponse")]
        System.Data.DataTable BuscarUsuarioNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioNombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioApellidoResponse")]
        System.Data.DataTable BuscarUsuarioApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioApellidoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioRol", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioRolResponse")]
        System.Data.DataTable BuscarUsuarioRol(string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioRol", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioRolResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioRolAsync(string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/Login", ReplyAction="http://tempuri.org/ILavadoraService/LoginResponse")]
        bool Login(string correo, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/Login", ReplyAction="http://tempuri.org/ILavadoraService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string correo, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarAceite", ReplyAction="http://tempuri.org/ILavadoraService/IngresarAceiteResponse")]
        void IngresarAceite(
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarAceite", ReplyAction="http://tempuri.org/ILavadoraService/IngresarAceiteResponse")]
        System.Threading.Tasks.Task IngresarAceiteAsync(
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarAceite", ReplyAction="http://tempuri.org/ILavadoraService/EditarAceiteResponse")]
        void EditarAceite(
                    int id, 
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarAceite", ReplyAction="http://tempuri.org/ILavadoraService/EditarAceiteResponse")]
        System.Threading.Tasks.Task EditarAceiteAsync(
                    int id, 
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarAceite", ReplyAction="http://tempuri.org/ILavadoraService/EliminarAceiteResponse")]
        void EliminarAceite(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarAceite", ReplyAction="http://tempuri.org/ILavadoraService/EliminarAceiteResponse")]
        System.Threading.Tasks.Task EliminarAceiteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarAceite", ReplyAction="http://tempuri.org/ILavadoraService/ValidarAceiteResponse")]
        bool ValidarAceite(string codigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarAceite", ReplyAction="http://tempuri.org/ILavadoraService/ValidarAceiteResponse")]
        System.Threading.Tasks.Task<bool> ValidarAceiteAsync(string codigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceite", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteResponse")]
        System.Data.DataTable ObtenerAceite();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceite", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarAceiteMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarAceiteMarcaResponse")]
        System.Data.DataTable BuscarAceiteMarca(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarAceiteMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarAceiteMarcaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarAceiteMarcaAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarAceiteCodigo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarAceiteCodigoResponse")]
        System.Data.DataTable BuscarAceiteCodigo(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarAceiteCodigo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarAceiteCodigoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarAceiteCodigoAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceiteSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteSAEResponse")]
        System.Data.DataTable ObtenerAceiteSAE(string sae);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceiteSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteSAEResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteSAEAsync(string sae);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerPresentacion", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerPresentacionResponse")]
        string[] ObtenerPresentacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerPresentacion", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerPresentacionResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerPresentacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerTipoAceite", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerTipoAceiteResponse")]
        string[] ObtenerTipoAceite();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerTipoAceite", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerTipoAceiteResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerTipoAceiteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerTipoCombustible", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerTipoCombustibleResponse")]
        string[] ObtenerTipoCombustible();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerTipoCombustible", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerTipoCombustibleResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerTipoCombustibleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerSAEResponse")]
        string[] ObtenerSAE();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerSAEResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerSAEAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerApi", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerApiResponse")]
        string[] ObtenerApi(int tipoCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerApi", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerApiResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerApiAsync(int tipoCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/IngresarFiltroResponse")]
        void IngresarFiltro(string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/IngresarFiltroResponse")]
        System.Threading.Tasks.Task IngresarFiltroAsync(string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/EditarFiltroResponse")]
        void EditarFiltro(int id, string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/EditarFiltroResponse")]
        System.Threading.Tasks.Task EditarFiltroAsync(int id, string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/EliminarFiltroResponse")]
        void EliminarFiltro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/EliminarFiltroResponse")]
        System.Threading.Tasks.Task EliminarFiltroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarCodigosFiltro", ReplyAction="http://tempuri.org/ILavadoraService/EliminarCodigosFiltroResponse")]
        void EliminarCodigosFiltro(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarCodigosFiltro", ReplyAction="http://tempuri.org/ILavadoraService/EliminarCodigosFiltroResponse")]
        System.Threading.Tasks.Task EliminarCodigosFiltroAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/LimpiarVehiculosBase", ReplyAction="http://tempuri.org/ILavadoraService/LimpiarVehiculosBaseResponse")]
        void LimpiarVehiculosBase(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/LimpiarVehiculosBase", ReplyAction="http://tempuri.org/ILavadoraService/LimpiarVehiculosBaseResponse")]
        System.Threading.Tasks.Task LimpiarVehiculosBaseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarVehiculoFiltro", ReplyAction="http://tempuri.org/ILavadoraService/IngresarVehiculoFiltroResponse")]
        void IngresarVehiculoFiltro(string codigoBarras, int idVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarVehiculoFiltro", ReplyAction="http://tempuri.org/ILavadoraService/IngresarVehiculoFiltroResponse")]
        System.Threading.Tasks.Task IngresarVehiculoFiltroAsync(string codigoBarras, int idVehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarCodigoFiltro", ReplyAction="http://tempuri.org/ILavadoraService/IngresarCodigoFiltroResponse")]
        void IngresarCodigoFiltro(string codigoBarras, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarCodigoFiltro", ReplyAction="http://tempuri.org/ILavadoraService/IngresarCodigoFiltroResponse")]
        System.Threading.Tasks.Task IngresarCodigoFiltroAsync(string codigoBarras, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerFiltros", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerFiltrosResponse")]
        System.Data.DataTable ObtenerFiltros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerFiltros", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerFiltrosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerFiltrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarFiltroMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarFiltroMarcaResponse")]
        System.Data.DataTable BuscarFiltroMarca(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarFiltroMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarFiltroMarcaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarFiltroMarcaAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarFiltroCodigo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarFiltroCodigoResponse")]
        System.Data.DataTable BuscarFiltroCodigo(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarFiltroCodigo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarFiltroCodigoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarFiltroCodigoAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ValidarFiltroResponse")]
        bool ValidarFiltro(string codigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ValidarFiltroResponse")]
        System.Threading.Tasks.Task<bool> ValidarFiltroAsync(string codigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerTipoFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerTipoFiltroResponse")]
        string[] ObtenerTipoFiltro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerTipoFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerTipoFiltroResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerTipoFiltroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculosFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculosFiltroResponse")]
        System.Data.DataTable ObtenerVehiculosFiltro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculosFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculosFiltroResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerVehiculosFiltroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerIdCodigosFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerIdCodigosFiltroResponse")]
        int[] ObtenerIdCodigosFiltro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerIdCodigosFiltro", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerIdCodigosFiltroResponse")]
        System.Threading.Tasks.Task<int[]> ObtenerIdCodigosFiltroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/LimpiarRelacionCodigosBase", ReplyAction="http://tempuri.org/ILavadoraService/LimpiarRelacionCodigosBaseResponse")]
        void LimpiarRelacionCodigosBase(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/LimpiarRelacionCodigosBase", ReplyAction="http://tempuri.org/ILavadoraService/LimpiarRelacionCodigosBaseResponse")]
        System.Threading.Tasks.Task LimpiarRelacionCodigosBaseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/LimpiarCodigosBase", ReplyAction="http://tempuri.org/ILavadoraService/LimpiarCodigosBaseResponse")]
        void LimpiarCodigosBase(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/LimpiarCodigosBase", ReplyAction="http://tempuri.org/ILavadoraService/LimpiarCodigosBaseResponse")]
        System.Threading.Tasks.Task LimpiarCodigosBaseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/GuardarIDsVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/GuardarIDsVehiculosResponse")]
        void GuardarIDsVehiculos(int[] idVehiculos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/GuardarIDsVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/GuardarIDsVehiculosResponse")]
        System.Threading.Tasks.Task GuardarIDsVehiculosAsync(int[] idVehiculos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerIDsVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerIDsVehiculosResponse")]
        int[] ObtenerIDsVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerIDsVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerIDsVehiculosResponse")]
        System.Threading.Tasks.Task<int[]> ObtenerIDsVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/GuardarEstadoListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/GuardarEstadoListaVehiculosResponse")]
        void GuardarEstadoListaVehiculos(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/GuardarEstadoListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/GuardarEstadoListaVehiculosResponse")]
        System.Threading.Tasks.Task GuardarEstadoListaVehiculosAsync(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerEstadoListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerEstadoListaVehiculosResponse")]
        bool ObtenerEstadoListaVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerEstadoListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerEstadoListaVehiculosResponse")]
        System.Threading.Tasks.Task<bool> ObtenerEstadoListaVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/GuardarIDListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/GuardarIDListaVehiculosResponse")]
        void GuardarIDListaVehiculos(int idFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/GuardarIDListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/GuardarIDListaVehiculosResponse")]
        System.Threading.Tasks.Task GuardarIDListaVehiculosAsync(int idFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerIDListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerIDListaVehiculosResponse")]
        int ObtenerIDListaVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerIDListaVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerIDListaVehiculosResponse")]
        System.Threading.Tasks.Task<int> ObtenerIDListaVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarProducto", ReplyAction="http://tempuri.org/ILavadoraService/IngresarProductoResponse")]
        void IngresarProducto(string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarProducto", ReplyAction="http://tempuri.org/ILavadoraService/IngresarProductoResponse")]
        System.Threading.Tasks.Task IngresarProductoAsync(string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarProducto", ReplyAction="http://tempuri.org/ILavadoraService/EditarProductoResponse")]
        void EditarProducto(int id, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarProducto", ReplyAction="http://tempuri.org/ILavadoraService/EditarProductoResponse")]
        System.Threading.Tasks.Task EditarProductoAsync(int id, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarProducto", ReplyAction="http://tempuri.org/ILavadoraService/EliminarProductoResponse")]
        void EliminarProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarProducto", ReplyAction="http://tempuri.org/ILavadoraService/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarProducto", ReplyAction="http://tempuri.org/ILavadoraService/ValidarProductoResponse")]
        bool ValidarProducto(string codigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarProducto", ReplyAction="http://tempuri.org/ILavadoraService/ValidarProductoResponse")]
        System.Threading.Tasks.Task<bool> ValidarProductoAsync(string codigoBarras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProducto", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProductoResponse")]
        System.Data.DataTable ObtenerProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProducto", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProductoMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProductoMarcaResponse")]
        System.Data.DataTable BuscarProductoMarca(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProductoMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProductoMarcaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProductoMarcaAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProductoCodigo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProductoCodigoResponse")]
        System.Data.DataTable BuscarProductoCodigo(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProductoCodigo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProductoCodigoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProductoCodigoAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarVehiculoResponse")]
        void IngresarVehiculo(string marca, string modelo, string anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarVehiculoResponse")]
        System.Threading.Tasks.Task IngresarVehiculoAsync(string marca, string modelo, string anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/EditarVehiculoResponse")]
        void EditarVehiculo(int id, string marca, string modelo, string anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/EditarVehiculoResponse")]
        System.Threading.Tasks.Task EditarVehiculoAsync(int id, string marca, string modelo, string anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/EliminarVehiculoResponse")]
        void EliminarVehiculo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/EliminarVehiculoResponse")]
        System.Threading.Tasks.Task EliminarVehiculoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculoResponse")]
        LavadoraLubricadora.LavadoraService.Vehiculo[] ObtenerVehiculo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculoResponse")]
        System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Vehiculo[]> ObtenerVehiculoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculoResponse")]
        string[] ObtenerMarcaVehiculo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerMarcaVehiculoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculoResponse")]
        string[] ObtenerModeloVehiculo(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerModeloVehiculoAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculoResponse")]
        string[] ObtenerAnioVehiculo(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerAnioVehiculoAsync(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculoResponse")]
        string[] ObtenerMotorVehiculo(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerMotorVehiculoAsync(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarVehiculoMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarVehiculoMarcaResponse")]
        System.Data.DataTable BuscarVehiculoMarca(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarVehiculoMarca", ReplyAction="http://tempuri.org/ILavadoraService/BuscarVehiculoMarcaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarVehiculoMarcaAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarVehiculoModelo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarVehiculoModeloResponse")]
        System.Data.DataTable BuscarVehiculoModelo(string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarVehiculoModelo", ReplyAction="http://tempuri.org/ILavadoraService/BuscarVehiculoModeloResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarVehiculoModeloAsync(string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarMotorVehiculoResponse")]
        void IngresarMotorVehiculo(string marca, string modelo, string anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarMotorVehiculoResponse")]
        System.Threading.Tasks.Task IngresarMotorVehiculoAsync(string marca, string modelo, string anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculosResponse")]
        System.Data.DataTable ObtenerVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerVehiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarCliente", ReplyAction="http://tempuri.org/ILavadoraService/IngresarClienteResponse")]
        void IngresarCliente(string nombre, string apellido, string telefono, string correo, string cedula, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarCliente", ReplyAction="http://tempuri.org/ILavadoraService/IngresarClienteResponse")]
        System.Threading.Tasks.Task IngresarClienteAsync(string nombre, string apellido, string telefono, string correo, string cedula, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarCliente", ReplyAction="http://tempuri.org/ILavadoraService/EditarClienteResponse")]
        void EditarCliente(int id, string nombre, string apellido, string telefono, string correo, string cedula, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarCliente", ReplyAction="http://tempuri.org/ILavadoraService/EditarClienteResponse")]
        System.Threading.Tasks.Task EditarClienteAsync(int id, string nombre, string apellido, string telefono, string correo, string cedula, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarCliente", ReplyAction="http://tempuri.org/ILavadoraService/EliminarClienteResponse")]
        void EliminarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarCliente", ReplyAction="http://tempuri.org/ILavadoraService/EliminarClienteResponse")]
        System.Threading.Tasks.Task EliminarClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerClientes", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerClientesResponse")]
        System.Data.DataTable ObtenerClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerClientes", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerClientesResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarClienteApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarClienteApellidoResponse")]
        System.Data.DataTable BuscarClienteApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarClienteApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarClienteApellidoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarClienteApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarClienteCedula", ReplyAction="http://tempuri.org/ILavadoraService/BuscarClienteCedulaResponse")]
        System.Data.DataTable BuscarClienteCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarClienteCedula", ReplyAction="http://tempuri.org/ILavadoraService/BuscarClienteCedulaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarClienteCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarClienteCedulaObj", ReplyAction="http://tempuri.org/ILavadoraService/BuscarClienteCedulaObjResponse")]
        LavadoraLubricadora.LavadoraService.Cliente BuscarClienteCedulaObj(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarClienteCedulaObj", ReplyAction="http://tempuri.org/ILavadoraService/BuscarClienteCedulaObjResponse")]
        System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Cliente> BuscarClienteCedulaObjAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarCliente", ReplyAction="http://tempuri.org/ILavadoraService/ValidarClienteResponse")]
        bool ValidarCliente(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarCliente", ReplyAction="http://tempuri.org/ILavadoraService/ValidarClienteResponse")]
        System.Threading.Tasks.Task<bool> ValidarClienteAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/IngresarProveedorResponse")]
        void IngresarProveedor(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/IngresarProveedorResponse")]
        System.Threading.Tasks.Task IngresarProveedorAsync(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILavadoraServiceChannel : LavadoraLubricadora.LavadoraService.ILavadoraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LavadoraServiceClient : System.ServiceModel.ClientBase<LavadoraLubricadora.LavadoraService.ILavadoraService>, LavadoraLubricadora.LavadoraService.ILavadoraService {
        
        public LavadoraServiceClient() {
        }
        
        public LavadoraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LavadoraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LavadoraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LavadoraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EditarProveedor(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            base.Channel.EditarProveedor(id, ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public System.Threading.Tasks.Task EditarProveedorAsync(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            return base.Channel.EditarProveedorAsync(id, ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public void EliminarProveedor(int id) {
            base.Channel.EliminarProveedor(id);
        }
        
        public System.Threading.Tasks.Task EliminarProveedorAsync(int id) {
            return base.Channel.EliminarProveedorAsync(id);
        }
        
        public System.Data.DataTable ObtenerProveedor() {
            return base.Channel.ObtenerProveedor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerProveedorAsync() {
            return base.Channel.ObtenerProveedorAsync();
        }
        
        public System.Data.DataTable BuscarProveedorNombre(string nombre) {
            return base.Channel.BuscarProveedorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorNombreAsync(string nombre) {
            return base.Channel.BuscarProveedorNombreAsync(nombre);
        }
        
        public System.Data.DataTable BuscarProveedorApellido(string apellido) {
            return base.Channel.BuscarProveedorApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorApellidoAsync(string apellido) {
            return base.Channel.BuscarProveedorApellidoAsync(apellido);
        }
        
        public System.Data.DataTable BuscarProveedorRuc(string ruc) {
            return base.Channel.BuscarProveedorRuc(ruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorRucAsync(string ruc) {
            return base.Channel.BuscarProveedorRucAsync(ruc);
        }
        
        public System.Data.DataTable BuscarProveedorEmpresa(string empresa) {
            return base.Channel.BuscarProveedorEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorEmpresaAsync(string empresa) {
            return base.Channel.BuscarProveedorEmpresaAsync(empresa);
        }
        
        public System.Data.DataTable ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public void IngresarUsuario(string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            base.Channel.IngresarUsuario(nombre, apellido, telefono, correo, rol, clave);
        }
        
        public System.Threading.Tasks.Task IngresarUsuarioAsync(string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            return base.Channel.IngresarUsuarioAsync(nombre, apellido, telefono, correo, rol, clave);
        }
        
        public void EditarUsuario(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            base.Channel.EditarUsuario(id, nombre, apellido, telefono, correo, rol, clave);
        }
        
        public System.Threading.Tasks.Task EditarUsuarioAsync(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            return base.Channel.EditarUsuarioAsync(id, nombre, apellido, telefono, correo, rol, clave);
        }
        
        public void EliminarUsuario(int id) {
            base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public System.Data.DataTable BuscarUsuarioNombre(string nombre) {
            return base.Channel.BuscarUsuarioNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioNombreAsync(string nombre) {
            return base.Channel.BuscarUsuarioNombreAsync(nombre);
        }
        
        public System.Data.DataTable BuscarUsuarioApellido(string apellido) {
            return base.Channel.BuscarUsuarioApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioApellidoAsync(string apellido) {
            return base.Channel.BuscarUsuarioApellidoAsync(apellido);
        }
        
        public System.Data.DataTable BuscarUsuarioRol(string rol) {
            return base.Channel.BuscarUsuarioRol(rol);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioRolAsync(string rol) {
            return base.Channel.BuscarUsuarioRolAsync(rol);
        }
        
        public bool Login(string correo, string clave) {
            return base.Channel.Login(correo, clave);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string correo, string clave) {
            return base.Channel.LoginAsync(correo, clave);
        }
        
        public void IngresarAceite(
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor) {
            base.Channel.IngresarAceite(marca, descripcion, codigoBarras, cantidad, cantidadMin, presentacion, sae, tipoCombustible, api, tipoAceite, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public System.Threading.Tasks.Task IngresarAceiteAsync(
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor) {
            return base.Channel.IngresarAceiteAsync(marca, descripcion, codigoBarras, cantidad, cantidadMin, presentacion, sae, tipoCombustible, api, tipoAceite, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public void EditarAceite(
                    int id, 
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor) {
            base.Channel.EditarAceite(id, marca, descripcion, codigoBarras, cantidad, cantidadMin, presentacion, sae, tipoCombustible, api, tipoAceite, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public System.Threading.Tasks.Task EditarAceiteAsync(
                    int id, 
                    string marca, 
                    string descripcion, 
                    string codigoBarras, 
                    int cantidad, 
                    int cantidadMin, 
                    string presentacion, 
                    string sae, 
                    string tipoCombustible, 
                    string api, 
                    string tipoAceite, 
                    double precioSinIva, 
                    double precioConIva, 
                    double precioMayor, 
                    double precioMenor, 
                    double margenMayor, 
                    double margenMenor) {
            return base.Channel.EditarAceiteAsync(id, marca, descripcion, codigoBarras, cantidad, cantidadMin, presentacion, sae, tipoCombustible, api, tipoAceite, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public void EliminarAceite(int id) {
            base.Channel.EliminarAceite(id);
        }
        
        public System.Threading.Tasks.Task EliminarAceiteAsync(int id) {
            return base.Channel.EliminarAceiteAsync(id);
        }
        
        public bool ValidarAceite(string codigoBarras) {
            return base.Channel.ValidarAceite(codigoBarras);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarAceiteAsync(string codigoBarras) {
            return base.Channel.ValidarAceiteAsync(codigoBarras);
        }
        
        public System.Data.DataTable ObtenerAceite() {
            return base.Channel.ObtenerAceite();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteAsync() {
            return base.Channel.ObtenerAceiteAsync();
        }
        
        public System.Data.DataTable BuscarAceiteMarca(string marca) {
            return base.Channel.BuscarAceiteMarca(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarAceiteMarcaAsync(string marca) {
            return base.Channel.BuscarAceiteMarcaAsync(marca);
        }
        
        public System.Data.DataTable BuscarAceiteCodigo(string marca) {
            return base.Channel.BuscarAceiteCodigo(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarAceiteCodigoAsync(string marca) {
            return base.Channel.BuscarAceiteCodigoAsync(marca);
        }
        
        public System.Data.DataTable ObtenerAceiteSAE(string sae) {
            return base.Channel.ObtenerAceiteSAE(sae);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteSAEAsync(string sae) {
            return base.Channel.ObtenerAceiteSAEAsync(sae);
        }
        
        public string[] ObtenerPresentacion() {
            return base.Channel.ObtenerPresentacion();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerPresentacionAsync() {
            return base.Channel.ObtenerPresentacionAsync();
        }
        
        public string[] ObtenerTipoAceite() {
            return base.Channel.ObtenerTipoAceite();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerTipoAceiteAsync() {
            return base.Channel.ObtenerTipoAceiteAsync();
        }
        
        public string[] ObtenerTipoCombustible() {
            return base.Channel.ObtenerTipoCombustible();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerTipoCombustibleAsync() {
            return base.Channel.ObtenerTipoCombustibleAsync();
        }
        
        public string[] ObtenerSAE() {
            return base.Channel.ObtenerSAE();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerSAEAsync() {
            return base.Channel.ObtenerSAEAsync();
        }
        
        public string[] ObtenerApi(int tipoCombustible) {
            return base.Channel.ObtenerApi(tipoCombustible);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerApiAsync(int tipoCombustible) {
            return base.Channel.ObtenerApiAsync(tipoCombustible);
        }
        
        public void IngresarFiltro(string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            base.Channel.IngresarFiltro(tipoFiltro, rosca, marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public System.Threading.Tasks.Task IngresarFiltroAsync(string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            return base.Channel.IngresarFiltroAsync(tipoFiltro, rosca, marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public void EditarFiltro(int id, string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            base.Channel.EditarFiltro(id, tipoFiltro, rosca, marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public System.Threading.Tasks.Task EditarFiltroAsync(int id, string tipoFiltro, string rosca, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            return base.Channel.EditarFiltroAsync(id, tipoFiltro, rosca, marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public void EliminarFiltro(int id) {
            base.Channel.EliminarFiltro(id);
        }
        
        public System.Threading.Tasks.Task EliminarFiltroAsync(int id) {
            return base.Channel.EliminarFiltroAsync(id);
        }
        
        public void EliminarCodigosFiltro(string codigo) {
            base.Channel.EliminarCodigosFiltro(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarCodigosFiltroAsync(string codigo) {
            return base.Channel.EliminarCodigosFiltroAsync(codigo);
        }
        
        public void LimpiarVehiculosBase(int id) {
            base.Channel.LimpiarVehiculosBase(id);
        }
        
        public System.Threading.Tasks.Task LimpiarVehiculosBaseAsync(int id) {
            return base.Channel.LimpiarVehiculosBaseAsync(id);
        }
        
        public void IngresarVehiculoFiltro(string codigoBarras, int idVehiculo) {
            base.Channel.IngresarVehiculoFiltro(codigoBarras, idVehiculo);
        }
        
        public System.Threading.Tasks.Task IngresarVehiculoFiltroAsync(string codigoBarras, int idVehiculo) {
            return base.Channel.IngresarVehiculoFiltroAsync(codigoBarras, idVehiculo);
        }
        
        public void IngresarCodigoFiltro(string codigoBarras, string codigo) {
            base.Channel.IngresarCodigoFiltro(codigoBarras, codigo);
        }
        
        public System.Threading.Tasks.Task IngresarCodigoFiltroAsync(string codigoBarras, string codigo) {
            return base.Channel.IngresarCodigoFiltroAsync(codigoBarras, codigo);
        }
        
        public System.Data.DataTable ObtenerFiltros() {
            return base.Channel.ObtenerFiltros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerFiltrosAsync() {
            return base.Channel.ObtenerFiltrosAsync();
        }
        
        public System.Data.DataTable BuscarFiltroMarca(string marca) {
            return base.Channel.BuscarFiltroMarca(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarFiltroMarcaAsync(string marca) {
            return base.Channel.BuscarFiltroMarcaAsync(marca);
        }
        
        public System.Data.DataTable BuscarFiltroCodigo(string marca) {
            return base.Channel.BuscarFiltroCodigo(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarFiltroCodigoAsync(string marca) {
            return base.Channel.BuscarFiltroCodigoAsync(marca);
        }
        
        public bool ValidarFiltro(string codigoBarras) {
            return base.Channel.ValidarFiltro(codigoBarras);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarFiltroAsync(string codigoBarras) {
            return base.Channel.ValidarFiltroAsync(codigoBarras);
        }
        
        public string[] ObtenerTipoFiltro() {
            return base.Channel.ObtenerTipoFiltro();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerTipoFiltroAsync() {
            return base.Channel.ObtenerTipoFiltroAsync();
        }
        
        public System.Data.DataTable ObtenerVehiculosFiltro(int id) {
            return base.Channel.ObtenerVehiculosFiltro(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerVehiculosFiltroAsync(int id) {
            return base.Channel.ObtenerVehiculosFiltroAsync(id);
        }
        
        public int[] ObtenerIdCodigosFiltro(int id) {
            return base.Channel.ObtenerIdCodigosFiltro(id);
        }
        
        public System.Threading.Tasks.Task<int[]> ObtenerIdCodigosFiltroAsync(int id) {
            return base.Channel.ObtenerIdCodigosFiltroAsync(id);
        }
        
        public void LimpiarRelacionCodigosBase(int id) {
            base.Channel.LimpiarRelacionCodigosBase(id);
        }
        
        public System.Threading.Tasks.Task LimpiarRelacionCodigosBaseAsync(int id) {
            return base.Channel.LimpiarRelacionCodigosBaseAsync(id);
        }
        
        public void LimpiarCodigosBase(int id) {
            base.Channel.LimpiarCodigosBase(id);
        }
        
        public System.Threading.Tasks.Task LimpiarCodigosBaseAsync(int id) {
            return base.Channel.LimpiarCodigosBaseAsync(id);
        }
        
        public void GuardarIDsVehiculos(int[] idVehiculos) {
            base.Channel.GuardarIDsVehiculos(idVehiculos);
        }
        
        public System.Threading.Tasks.Task GuardarIDsVehiculosAsync(int[] idVehiculos) {
            return base.Channel.GuardarIDsVehiculosAsync(idVehiculos);
        }
        
        public int[] ObtenerIDsVehiculos() {
            return base.Channel.ObtenerIDsVehiculos();
        }
        
        public System.Threading.Tasks.Task<int[]> ObtenerIDsVehiculosAsync() {
            return base.Channel.ObtenerIDsVehiculosAsync();
        }
        
        public void GuardarEstadoListaVehiculos(bool estado) {
            base.Channel.GuardarEstadoListaVehiculos(estado);
        }
        
        public System.Threading.Tasks.Task GuardarEstadoListaVehiculosAsync(bool estado) {
            return base.Channel.GuardarEstadoListaVehiculosAsync(estado);
        }
        
        public bool ObtenerEstadoListaVehiculos() {
            return base.Channel.ObtenerEstadoListaVehiculos();
        }
        
        public System.Threading.Tasks.Task<bool> ObtenerEstadoListaVehiculosAsync() {
            return base.Channel.ObtenerEstadoListaVehiculosAsync();
        }
        
        public void GuardarIDListaVehiculos(int idFiltro) {
            base.Channel.GuardarIDListaVehiculos(idFiltro);
        }
        
        public System.Threading.Tasks.Task GuardarIDListaVehiculosAsync(int idFiltro) {
            return base.Channel.GuardarIDListaVehiculosAsync(idFiltro);
        }
        
        public int ObtenerIDListaVehiculos() {
            return base.Channel.ObtenerIDListaVehiculos();
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIDListaVehiculosAsync() {
            return base.Channel.ObtenerIDListaVehiculosAsync();
        }
        
        public void IngresarProducto(string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            base.Channel.IngresarProducto(marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public System.Threading.Tasks.Task IngresarProductoAsync(string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            return base.Channel.IngresarProductoAsync(marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public void EditarProducto(int id, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            base.Channel.EditarProducto(id, marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public System.Threading.Tasks.Task EditarProductoAsync(int id, string marca, string descripcion, string codigoBarras, int cantidad, int cantidadMin, double precioSinIva, double precioConIva, double precioMayor, double precioMenor, double margenMayor, double margenMenor) {
            return base.Channel.EditarProductoAsync(id, marca, descripcion, codigoBarras, cantidad, cantidadMin, precioSinIva, precioConIva, precioMayor, precioMenor, margenMayor, margenMenor);
        }
        
        public void EliminarProducto(int id) {
            base.Channel.EliminarProducto(id);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(int id) {
            return base.Channel.EliminarProductoAsync(id);
        }
        
        public bool ValidarProducto(string codigoBarras) {
            return base.Channel.ValidarProducto(codigoBarras);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarProductoAsync(string codigoBarras) {
            return base.Channel.ValidarProductoAsync(codigoBarras);
        }
        
        public System.Data.DataTable ObtenerProducto() {
            return base.Channel.ObtenerProducto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerProductoAsync() {
            return base.Channel.ObtenerProductoAsync();
        }
        
        public System.Data.DataTable BuscarProductoMarca(string marca) {
            return base.Channel.BuscarProductoMarca(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProductoMarcaAsync(string marca) {
            return base.Channel.BuscarProductoMarcaAsync(marca);
        }
        
        public System.Data.DataTable BuscarProductoCodigo(string marca) {
            return base.Channel.BuscarProductoCodigo(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProductoCodigoAsync(string marca) {
            return base.Channel.BuscarProductoCodigoAsync(marca);
        }
        
        public void IngresarVehiculo(string marca, string modelo, string anio, string tipoMotor) {
            base.Channel.IngresarVehiculo(marca, modelo, anio, tipoMotor);
        }
        
        public System.Threading.Tasks.Task IngresarVehiculoAsync(string marca, string modelo, string anio, string tipoMotor) {
            return base.Channel.IngresarVehiculoAsync(marca, modelo, anio, tipoMotor);
        }
        
        public void EditarVehiculo(int id, string marca, string modelo, string anio, string tipoMotor) {
            base.Channel.EditarVehiculo(id, marca, modelo, anio, tipoMotor);
        }
        
        public System.Threading.Tasks.Task EditarVehiculoAsync(int id, string marca, string modelo, string anio, string tipoMotor) {
            return base.Channel.EditarVehiculoAsync(id, marca, modelo, anio, tipoMotor);
        }
        
        public void EliminarVehiculo(int id) {
            base.Channel.EliminarVehiculo(id);
        }
        
        public System.Threading.Tasks.Task EliminarVehiculoAsync(int id) {
            return base.Channel.EliminarVehiculoAsync(id);
        }
        
        public LavadoraLubricadora.LavadoraService.Vehiculo[] ObtenerVehiculo() {
            return base.Channel.ObtenerVehiculo();
        }
        
        public System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Vehiculo[]> ObtenerVehiculoAsync() {
            return base.Channel.ObtenerVehiculoAsync();
        }
        
        public string[] ObtenerMarcaVehiculo() {
            return base.Channel.ObtenerMarcaVehiculo();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerMarcaVehiculoAsync() {
            return base.Channel.ObtenerMarcaVehiculoAsync();
        }
        
        public string[] ObtenerModeloVehiculo(string marca) {
            return base.Channel.ObtenerModeloVehiculo(marca);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerModeloVehiculoAsync(string marca) {
            return base.Channel.ObtenerModeloVehiculoAsync(marca);
        }
        
        public string[] ObtenerAnioVehiculo(string marca, string modelo) {
            return base.Channel.ObtenerAnioVehiculo(marca, modelo);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerAnioVehiculoAsync(string marca, string modelo) {
            return base.Channel.ObtenerAnioVehiculoAsync(marca, modelo);
        }
        
        public string[] ObtenerMotorVehiculo(string marca, string modelo) {
            return base.Channel.ObtenerMotorVehiculo(marca, modelo);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerMotorVehiculoAsync(string marca, string modelo) {
            return base.Channel.ObtenerMotorVehiculoAsync(marca, modelo);
        }
        
        public System.Data.DataTable BuscarVehiculoMarca(string marca) {
            return base.Channel.BuscarVehiculoMarca(marca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarVehiculoMarcaAsync(string marca) {
            return base.Channel.BuscarVehiculoMarcaAsync(marca);
        }
        
        public System.Data.DataTable BuscarVehiculoModelo(string modelo) {
            return base.Channel.BuscarVehiculoModelo(modelo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarVehiculoModeloAsync(string modelo) {
            return base.Channel.BuscarVehiculoModeloAsync(modelo);
        }
        
        public void IngresarMotorVehiculo(string marca, string modelo, string anio, string tipoMotor) {
            base.Channel.IngresarMotorVehiculo(marca, modelo, anio, tipoMotor);
        }
        
        public System.Threading.Tasks.Task IngresarMotorVehiculoAsync(string marca, string modelo, string anio, string tipoMotor) {
            return base.Channel.IngresarMotorVehiculoAsync(marca, modelo, anio, tipoMotor);
        }
        
        public System.Data.DataTable ObtenerVehiculos() {
            return base.Channel.ObtenerVehiculos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerVehiculosAsync() {
            return base.Channel.ObtenerVehiculosAsync();
        }
        
        public void IngresarCliente(string nombre, string apellido, string telefono, string correo, string cedula, string direccion) {
            base.Channel.IngresarCliente(nombre, apellido, telefono, correo, cedula, direccion);
        }
        
        public System.Threading.Tasks.Task IngresarClienteAsync(string nombre, string apellido, string telefono, string correo, string cedula, string direccion) {
            return base.Channel.IngresarClienteAsync(nombre, apellido, telefono, correo, cedula, direccion);
        }
        
        public void EditarCliente(int id, string nombre, string apellido, string telefono, string correo, string cedula, string direccion) {
            base.Channel.EditarCliente(id, nombre, apellido, telefono, correo, cedula, direccion);
        }
        
        public System.Threading.Tasks.Task EditarClienteAsync(int id, string nombre, string apellido, string telefono, string correo, string cedula, string direccion) {
            return base.Channel.EditarClienteAsync(id, nombre, apellido, telefono, correo, cedula, direccion);
        }
        
        public void EliminarCliente(int id) {
            base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task EliminarClienteAsync(int id) {
            return base.Channel.EliminarClienteAsync(id);
        }
        
        public System.Data.DataTable ObtenerClientes() {
            return base.Channel.ObtenerClientes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerClientesAsync() {
            return base.Channel.ObtenerClientesAsync();
        }
        
        public System.Data.DataTable BuscarClienteApellido(string apellido) {
            return base.Channel.BuscarClienteApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarClienteApellidoAsync(string apellido) {
            return base.Channel.BuscarClienteApellidoAsync(apellido);
        }
        
        public System.Data.DataTable BuscarClienteCedula(string cedula) {
            return base.Channel.BuscarClienteCedula(cedula);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarClienteCedulaAsync(string cedula) {
            return base.Channel.BuscarClienteCedulaAsync(cedula);
        }
        
        public LavadoraLubricadora.LavadoraService.Cliente BuscarClienteCedulaObj(string cedula) {
            return base.Channel.BuscarClienteCedulaObj(cedula);
        }
        
        public System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Cliente> BuscarClienteCedulaObjAsync(string cedula) {
            return base.Channel.BuscarClienteCedulaObjAsync(cedula);
        }
        
        public bool ValidarCliente(string cedula) {
            return base.Channel.ValidarCliente(cedula);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarClienteAsync(string cedula) {
            return base.Channel.ValidarClienteAsync(cedula);
        }
        
        public void IngresarProveedor(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            base.Channel.IngresarProveedor(ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public System.Threading.Tasks.Task IngresarProveedorAsync(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            return base.Channel.IngresarProveedorAsync(ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
    }
}
