//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavadoraLubricadora.LavadoraService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasesLavadora")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadMinimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoBarrasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioCompraConIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioCompraSinIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioMargenxMayorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioMargenxMenorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaxMayorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioVentaxMenorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadMinima {
            get {
                return this.CantidadMinimaField;
            }
            set {
                if ((this.CantidadMinimaField.Equals(value) != true)) {
                    this.CantidadMinimaField = value;
                    this.RaisePropertyChanged("CantidadMinima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoBarras {
            get {
                return this.CodigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoBarrasField, value) != true)) {
                    this.CodigoBarrasField = value;
                    this.RaisePropertyChanged("CodigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioCompraConIva {
            get {
                return this.PrecioCompraConIvaField;
            }
            set {
                if ((this.PrecioCompraConIvaField.Equals(value) != true)) {
                    this.PrecioCompraConIvaField = value;
                    this.RaisePropertyChanged("PrecioCompraConIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioCompraSinIva {
            get {
                return this.PrecioCompraSinIvaField;
            }
            set {
                if ((this.PrecioCompraSinIvaField.Equals(value) != true)) {
                    this.PrecioCompraSinIvaField = value;
                    this.RaisePropertyChanged("PrecioCompraSinIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioMargenxMayor {
            get {
                return this.PrecioMargenxMayorField;
            }
            set {
                if ((this.PrecioMargenxMayorField.Equals(value) != true)) {
                    this.PrecioMargenxMayorField = value;
                    this.RaisePropertyChanged("PrecioMargenxMayor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioMargenxMenor {
            get {
                return this.PrecioMargenxMenorField;
            }
            set {
                if ((this.PrecioMargenxMenorField.Equals(value) != true)) {
                    this.PrecioMargenxMenorField = value;
                    this.RaisePropertyChanged("PrecioMargenxMenor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVentaxMayor {
            get {
                return this.PrecioVentaxMayorField;
            }
            set {
                if ((this.PrecioVentaxMayorField.Equals(value) != true)) {
                    this.PrecioVentaxMayorField = value;
                    this.RaisePropertyChanged("PrecioVentaxMayor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVentaxMenor {
            get {
                return this.PrecioVentaxMenorField;
            }
            set {
                if ((this.PrecioVentaxMenorField.Equals(value) != true)) {
                    this.PrecioVentaxMenorField = value;
                    this.RaisePropertyChanged("PrecioVentaxMenor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasesLavadora")]
    [System.SerializableAttribute()]
    public partial class Vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TipoMotorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVehiculo {
            get {
                return this.IdVehiculoField;
            }
            set {
                if ((this.IdVehiculoField.Equals(value) != true)) {
                    this.IdVehiculoField = value;
                    this.RaisePropertyChanged("IdVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] TipoMotor {
            get {
                return this.TipoMotorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMotorField, value) != true)) {
                    this.TipoMotorField = value;
                    this.RaisePropertyChanged("TipoMotor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LavadoraService.ILavadoraService")]
    public interface ILavadoraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceite", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteResponse")]
        System.Data.DataTable ObtenerAceite();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceite", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceiteSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteSAEResponse")]
        System.Data.DataTable ObtenerAceiteSAE(string sae);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAceiteSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAceiteSAEResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteSAEAsync(string sae);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProducto", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProductoResponse")]
        LavadoraLubricadora.LavadoraService.Producto ObtenerProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProducto", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Producto> ObtenerProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculoResponse")]
        LavadoraLubricadora.LavadoraService.Vehiculo[] ObtenerVehiculo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculoResponse")]
        System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Vehiculo[]> ObtenerVehiculoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerSAEResponse")]
        string[] ObtenerSAE();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerSAE", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerSAEResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerSAEAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculoResponse")]
        string[] ObtenerMarcaVehiculo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMarcaVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerMarcaVehiculoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculoResponse")]
        string[] ObtenerModeloVehiculo(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerModeloVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerModeloVehiculoAsync(string marca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculoResponse")]
        string[] ObtenerAnioVehiculo(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerAnioVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerAnioVehiculoAsync(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculoResponse")]
        string[] ObtenerMotorVehiculo(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerMotorVehiculoResponse")]
        System.Threading.Tasks.Task<string[]> ObtenerMotorVehiculoAsync(string marca, string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarVehiculoResponse")]
        void IngresarVehiculo(string marca, string modelo, int anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarVehiculoResponse")]
        System.Threading.Tasks.Task IngresarVehiculoAsync(string marca, string modelo, int anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/EditarVehiculoResponse")]
        void EditarVehiculo(int id, string marca, string modelo, int anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/EditarVehiculoResponse")]
        System.Threading.Tasks.Task EditarVehiculoAsync(int id, string marca, string modelo, int anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarMotorVehiculoResponse")]
        void IngresarMotorVehiculo(string marca, string modelo, int anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarMotorVehiculo", ReplyAction="http://tempuri.org/ILavadoraService/IngresarMotorVehiculoResponse")]
        System.Threading.Tasks.Task IngresarMotorVehiculoAsync(string marca, string modelo, int anio, string tipoMotor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/Login", ReplyAction="http://tempuri.org/ILavadoraService/LoginResponse")]
        bool Login(string correo, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/Login", ReplyAction="http://tempuri.org/ILavadoraService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string correo, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProveedor", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProveedorResponse")]
        System.Data.DataTable ObtenerProveedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerProveedor", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerProveedorResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerProveedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorNombreResponse")]
        System.Data.DataTable BuscarProveedorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorNombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorApellidoResponse")]
        System.Data.DataTable BuscarProveedorApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorApellidoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorRuc", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorRucResponse")]
        System.Data.DataTable BuscarProveedorRuc(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorRuc", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorRucResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorRucAsync(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresa", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresaResponse")]
        System.Data.DataTable BuscarProveedorEmpresa(string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresa", ReplyAction="http://tempuri.org/ILavadoraService/BuscarProveedorEmpresaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorEmpresaAsync(string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/IngresarProveedorResponse")]
        void IngresarProveedor(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/IngresarProveedorResponse")]
        System.Threading.Tasks.Task IngresarProveedorAsync(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EditarProveedorResponse")]
        void EditarProveedor(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EditarProveedorResponse")]
        System.Threading.Tasks.Task EditarProveedorAsync(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EliminarProveedorResponse")]
        void EliminarProveedor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarProveedor", ReplyAction="http://tempuri.org/ILavadoraService/EliminarProveedorResponse")]
        System.Threading.Tasks.Task EliminarProveedorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerUsuarios", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerUsuariosResponse")]
        System.Data.DataTable ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerUsuarios", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/IngresarUsuarioResponse")]
        void IngresarUsuario(string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/IngresarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/IngresarUsuarioResponse")]
        System.Threading.Tasks.Task IngresarUsuarioAsync(string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EditarUsuarioResponse")]
        void EditarUsuario(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EditarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EditarUsuarioResponse")]
        System.Threading.Tasks.Task EditarUsuarioAsync(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EliminarUsuarioResponse")]
        void EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/EliminarUsuario", ReplyAction="http://tempuri.org/ILavadoraService/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioNombreResponse")]
        System.Data.DataTable BuscarUsuarioNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioNombre", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioNombreResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioApellidoResponse")]
        System.Data.DataTable BuscarUsuarioApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioApellido", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioApellidoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioRol", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioRolResponse")]
        System.Data.DataTable BuscarUsuarioRol(string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/BuscarUsuarioRol", ReplyAction="http://tempuri.org/ILavadoraService/BuscarUsuarioRolResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioRolAsync(string rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarClave", ReplyAction="http://tempuri.org/ILavadoraService/ValidarClaveResponse")]
        bool ValidarClave(int id, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ValidarClave", ReplyAction="http://tempuri.org/ILavadoraService/ValidarClaveResponse")]
        System.Threading.Tasks.Task<bool> ValidarClaveAsync(int id, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculosResponse")]
        System.Data.DataTable ObtenerVehiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILavadoraService/ObtenerVehiculos", ReplyAction="http://tempuri.org/ILavadoraService/ObtenerVehiculosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerVehiculosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILavadoraServiceChannel : LavadoraLubricadora.LavadoraService.ILavadoraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LavadoraServiceClient : System.ServiceModel.ClientBase<LavadoraLubricadora.LavadoraService.ILavadoraService>, LavadoraLubricadora.LavadoraService.ILavadoraService {
        
        public LavadoraServiceClient() {
        }
        
        public LavadoraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LavadoraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LavadoraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LavadoraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ObtenerAceite() {
            return base.Channel.ObtenerAceite();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteAsync() {
            return base.Channel.ObtenerAceiteAsync();
        }
        
        public System.Data.DataTable ObtenerAceiteSAE(string sae) {
            return base.Channel.ObtenerAceiteSAE(sae);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerAceiteSAEAsync(string sae) {
            return base.Channel.ObtenerAceiteSAEAsync(sae);
        }
        
        public LavadoraLubricadora.LavadoraService.Producto ObtenerProducto(int id) {
            return base.Channel.ObtenerProducto(id);
        }
        
        public System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Producto> ObtenerProductoAsync(int id) {
            return base.Channel.ObtenerProductoAsync(id);
        }
        
        public LavadoraLubricadora.LavadoraService.Vehiculo[] ObtenerVehiculo() {
            return base.Channel.ObtenerVehiculo();
        }
        
        public System.Threading.Tasks.Task<LavadoraLubricadora.LavadoraService.Vehiculo[]> ObtenerVehiculoAsync() {
            return base.Channel.ObtenerVehiculoAsync();
        }
        
        public string[] ObtenerSAE() {
            return base.Channel.ObtenerSAE();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerSAEAsync() {
            return base.Channel.ObtenerSAEAsync();
        }
        
        public string[] ObtenerMarcaVehiculo() {
            return base.Channel.ObtenerMarcaVehiculo();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerMarcaVehiculoAsync() {
            return base.Channel.ObtenerMarcaVehiculoAsync();
        }
        
        public string[] ObtenerModeloVehiculo(string marca) {
            return base.Channel.ObtenerModeloVehiculo(marca);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerModeloVehiculoAsync(string marca) {
            return base.Channel.ObtenerModeloVehiculoAsync(marca);
        }
        
        public string[] ObtenerAnioVehiculo(string marca, string modelo) {
            return base.Channel.ObtenerAnioVehiculo(marca, modelo);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerAnioVehiculoAsync(string marca, string modelo) {
            return base.Channel.ObtenerAnioVehiculoAsync(marca, modelo);
        }
        
        public string[] ObtenerMotorVehiculo(string marca, string modelo) {
            return base.Channel.ObtenerMotorVehiculo(marca, modelo);
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerMotorVehiculoAsync(string marca, string modelo) {
            return base.Channel.ObtenerMotorVehiculoAsync(marca, modelo);
        }
        
        public void IngresarVehiculo(string marca, string modelo, int anio, string tipoMotor) {
            base.Channel.IngresarVehiculo(marca, modelo, anio, tipoMotor);
        }
        
        public System.Threading.Tasks.Task IngresarVehiculoAsync(string marca, string modelo, int anio, string tipoMotor) {
            return base.Channel.IngresarVehiculoAsync(marca, modelo, anio, tipoMotor);
        }
        
        public void EditarVehiculo(int id, string marca, string modelo, int anio, string tipoMotor) {
            base.Channel.EditarVehiculo(id, marca, modelo, anio, tipoMotor);
        }
        
        public System.Threading.Tasks.Task EditarVehiculoAsync(int id, string marca, string modelo, int anio, string tipoMotor) {
            return base.Channel.EditarVehiculoAsync(id, marca, modelo, anio, tipoMotor);
        }
        
        public void IngresarMotorVehiculo(string marca, string modelo, int anio, string tipoMotor) {
            base.Channel.IngresarMotorVehiculo(marca, modelo, anio, tipoMotor);
        }
        
        public System.Threading.Tasks.Task IngresarMotorVehiculoAsync(string marca, string modelo, int anio, string tipoMotor) {
            return base.Channel.IngresarMotorVehiculoAsync(marca, modelo, anio, tipoMotor);
        }
        
        public bool Login(string correo, string clave) {
            return base.Channel.Login(correo, clave);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string correo, string clave) {
            return base.Channel.LoginAsync(correo, clave);
        }
        
        public System.Data.DataTable ObtenerProveedor() {
            return base.Channel.ObtenerProveedor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerProveedorAsync() {
            return base.Channel.ObtenerProveedorAsync();
        }
        
        public System.Data.DataTable BuscarProveedorNombre(string nombre) {
            return base.Channel.BuscarProveedorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorNombreAsync(string nombre) {
            return base.Channel.BuscarProveedorNombreAsync(nombre);
        }
        
        public System.Data.DataTable BuscarProveedorApellido(string apellido) {
            return base.Channel.BuscarProveedorApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorApellidoAsync(string apellido) {
            return base.Channel.BuscarProveedorApellidoAsync(apellido);
        }
        
        public System.Data.DataTable BuscarProveedorRuc(string ruc) {
            return base.Channel.BuscarProveedorRuc(ruc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorRucAsync(string ruc) {
            return base.Channel.BuscarProveedorRucAsync(ruc);
        }
        
        public System.Data.DataTable BuscarProveedorEmpresa(string empresa) {
            return base.Channel.BuscarProveedorEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProveedorEmpresaAsync(string empresa) {
            return base.Channel.BuscarProveedorEmpresaAsync(empresa);
        }
        
        public void IngresarProveedor(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            base.Channel.IngresarProveedor(ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public System.Threading.Tasks.Task IngresarProveedorAsync(string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            return base.Channel.IngresarProveedorAsync(ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public void EditarProveedor(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            base.Channel.EditarProveedor(id, ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public System.Threading.Tasks.Task EditarProveedorAsync(int id, string ruc, string nombre, string apellido, string telefono, string correo, string direccion, string empresa) {
            return base.Channel.EditarProveedorAsync(id, ruc, nombre, apellido, telefono, correo, direccion, empresa);
        }
        
        public void EliminarProveedor(int id) {
            base.Channel.EliminarProveedor(id);
        }
        
        public System.Threading.Tasks.Task EliminarProveedorAsync(int id) {
            return base.Channel.EliminarProveedorAsync(id);
        }
        
        public System.Data.DataTable ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public void IngresarUsuario(string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            base.Channel.IngresarUsuario(nombre, apellido, telefono, correo, rol, clave);
        }
        
        public System.Threading.Tasks.Task IngresarUsuarioAsync(string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            return base.Channel.IngresarUsuarioAsync(nombre, apellido, telefono, correo, rol, clave);
        }
        
        public void EditarUsuario(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            base.Channel.EditarUsuario(id, nombre, apellido, telefono, correo, rol, clave);
        }
        
        public System.Threading.Tasks.Task EditarUsuarioAsync(int id, string nombre, string apellido, string telefono, string correo, string rol, string clave) {
            return base.Channel.EditarUsuarioAsync(id, nombre, apellido, telefono, correo, rol, clave);
        }
        
        public void EliminarUsuario(int id) {
            base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public System.Data.DataTable BuscarUsuarioNombre(string nombre) {
            return base.Channel.BuscarUsuarioNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioNombreAsync(string nombre) {
            return base.Channel.BuscarUsuarioNombreAsync(nombre);
        }
        
        public System.Data.DataTable BuscarUsuarioApellido(string apellido) {
            return base.Channel.BuscarUsuarioApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioApellidoAsync(string apellido) {
            return base.Channel.BuscarUsuarioApellidoAsync(apellido);
        }
        
        public System.Data.DataTable BuscarUsuarioRol(string rol) {
            return base.Channel.BuscarUsuarioRol(rol);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuarioRolAsync(string rol) {
            return base.Channel.BuscarUsuarioRolAsync(rol);
        }
        
        public bool ValidarClave(int id, string clave) {
            return base.Channel.ValidarClave(id, clave);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarClaveAsync(int id, string clave) {
            return base.Channel.ValidarClaveAsync(id, clave);
        }
        
        public System.Data.DataTable ObtenerVehiculos() {
            return base.Channel.ObtenerVehiculos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerVehiculosAsync() {
            return base.Channel.ObtenerVehiculosAsync();
        }
    }
}
